### ISSUE TITLE
Create draft content for Design Guide

### ISSUE THREAD

**Issue by netplusdesign** [cfpb/email-templates#2]
Draft content is now on wiki…

https://github.com/cfpb/email-templates/wiki/Responsive-Email-Templates---Content-for-Design-Guide

Please take a look and make edits or add comments to this issue.

**Comment by Scotchester** [comment]
On your [Subject examples](https://github.com/cfpb/email-templates/wiki/Responsive-Email-Templates---Content-for-Design-Guide#subject): I'm not sure I agree.

If the `From` data shows "Consumer Financial Protection Bureau" and the `Subject` only says "Your account activation was successful", I would wonder "What account?" Maybe we could reasonably expect people to be aware of the things they've recently registered for, but I don't think including the name of the app/site/system in the Subject (in this case, "CFPB Extranet") is overly redundant.

**Comment by Scotchester** [comment]
Otherwise, I think this is great!

When the actual email design is finalized, we should include guidelines for that, and maybe front-end guidance, as well. Otherwise, this page would stand out as the only page in the manual that talks strictly about written content.

**Comment by netplusdesign** [comment]
Thanks @Scotchester , re: subject examples, maybe I'm thinking too Extranet specific, or maybe I chose a poor example. Sorry to ask but do you have a specific example in mind where the subject included a reference to the 'from' line? To me it's like referring to yourself in the 3rd person.

**Comment by hkeeler** [comment]
Yeah, we've gone back and forth on the Extranet project around whether `From:` and/or `Subject:` should designate the source of the email.  We originally had:

```
Subject: [CFPB Extranet] - Instructions for activating your Extranet account
From: CFPB Extranet <CFPB_Extranet_Support@cfpb.gov>
```

...but decided to ditch the `Subject:` prefix since it was a dupe of the `From:`

In the case of Extranet, the users are already expecting an email from us, so they have some context.  Perhaps less so for other emails, such as Consumer Response.

In looking at a bunch of transactional emails I've received, its was a pretty even split of those that did and did not include the organization's name in the subject.

**Comment by Scotchester** [comment]
@netplusdesign I take your general point and don't have a specific example in mind to refute it. I think what's going on in my head is that there's a distinction between "Consumer Financial Protection Bureau", the organization, and "CFPB Extranet", the system. So if you have

**From:** Consumer Financial Protection Bureau
**Subject:** [CFPB Extranet] - Instructions for activating your account

That's not redundant, to me. (Note the removal of the second use of "Extranet" from @hkeeler's example, and note the lack of email address in the from line, because email clients only show the friendly `From` name in the inbox listing.)

Now, if we have "CFPB Extranet" as the `From` name, then I would absolutely agree with not including it in the subject line. 'cause that's straight up redundant :)

See what I mean?

**Comment by Dnpizarro** [comment]
@netplusdesign generally, I think the break down looks great! I wonder if it would be helpful when we're illustrating examples to actually show an image of our final designs. That way users have a visual context for the formatting.

**Comment by Scotchester** [comment]
It might also be worth noting that "Consumer Financial Protection Bureau" as a `From` name is probably long enough to get cut off in a lot of email clients.

**Comment by netplusdesign** [comment]
After a quick chat at standup, it seems like it would make sense if the From field was more specific and less generic for some types of emails. Particularly those addressed to institutions in the case of the Extranet. 

In the case of the Extranet, the From field could be 'CFPB Extranet Support', or 'CFPB Extranet' for short. This would free up the subject line to focus on the intent of the email and not clarify who within the bureau the email is coming from.

For consumers, the From field should continue to be the full bureau name to reduce communicating information about the organizational structure of the bureau when it is really not helpful to the task at hand.

Make sense? I will update the wiki.

**Comment by netplusdesign** [comment]
Wiki 'From' field section updated.

**Comment by netplusdesign** [comment]
PR submitted to design-manual. Closing this issue, thanks all.
